In [1]:
import pandas as pd  # 데이터 전처리를 위해서 
import seaborn as sns # 시각화를 위해서 

df = pd.read_csv('c:\\data\\mushrooms.csv')

In [2]:
df = pd.get_dummies(df)
#print(df.shape)  # (8124, 23)
print(df)
print(df.shape) # (8124, 119)

# get_dummies 함수를 이용해서 값의 종류에 따라 
# 전부 0 아니면 1로 변환함 

      type_edible  type_poisonous  cap_shape_bell  cap_shape_conical  \
0               0               1               0                  0   
1               1               0               0                  0   
2               1               0               1                  0   
3               0               1               0                  0   
4               1               0               0                  0   
...           ...             ...             ...                ...   
8119            1               0               0                  0   
8120            1               0               0                  0   
8121            1               0               0                  0   
8122            0               1               0                  0   
8123            1               0               0                  0   

      cap_shape_convex  cap_shape_flat  cap_shape_knobbed  cap_shape_sunken  \
0                    1               0                  

In [3]:
# DataFrame 확인
print(df.shape)  # (8124, 23)
print(df.info())  # 전부 object (문자)형으로 되어있음
print(df.describe())

(8124, 119)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Columns: 119 entries, type_edible to habitat_woods
dtypes: uint8(119)
memory usage: 944.2 KB
None
       type_edible  type_poisonous  cap_shape_bell  cap_shape_conical  \
count  8124.000000     8124.000000     8124.000000        8124.000000   
mean      0.517971        0.482029        0.055638           0.000492   
std       0.499708        0.499708        0.229235           0.022185   
min       0.000000        0.000000        0.000000           0.000000   
25%       0.000000        0.000000        0.000000           0.000000   
50%       1.000000        0.000000        0.000000           0.000000   
75%       1.000000        1.000000        0.000000           0.000000   
max       1.000000        1.000000        1.000000           1.000000   

       cap_shape_convex  cap_shape_flat  cap_shape_knobbed  cap_shape_sunken  \
count       8124.000000     8124.000000        8124.000000       8124.000000  

In [4]:
# X = 전체 행, 마지막 열 제외한 모든 열 데이터 -> n차원 공간의 포인트
X = df.iloc[:,2:].to_numpy() 
y = df.iloc[:,1].to_numpy()   
print(X)
print(y)

print(df.shape)  # (8124, 119)
print(len(X))  # 8124
print(len(y))  # 8124

[[0 0 1 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[1 0 0 ... 0 1 0]
(8124, 119)
8124
8124


In [5]:
from sklearn import preprocessing 

X=preprocessing.StandardScaler().fit(X).transform(X)  
print(X)
#X=preprocessing.MinMaxScaler().fit(X).transform(X) 


[[-0.24272523 -0.02219484  1.10548662 ...  4.59086996 -0.15558197
  -0.7953846 ]
 [-0.24272523 -0.02219484  1.10548662 ... -0.21782364 -0.15558197
  -0.7953846 ]
 [ 4.11988487 -0.02219484 -0.90457902 ... -0.21782364 -0.15558197
  -0.7953846 ]
 ...
 [-0.24272523 -0.02219484 -0.90457902 ... -0.21782364 -0.15558197
  -0.7953846 ]
 [-0.24272523 -0.02219484 -0.90457902 ... -0.21782364 -0.15558197
  -0.7953846 ]
 [-0.24272523 -0.02219484  1.10548662 ... -0.21782364 -0.15558197
  -0.7953846 ]]


In [6]:
from sklearn.model_selection import train_test_split 
                                                                                     
# 훈련 데이터 75, 테스트 데이터 25으로 나눈다. 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state = 10)

print(X_train.shape)   # (6093, 22)
print(y_train.shape)   # (6093,)


(6093, 117)
(6093,)


In [7]:
# sklearn 라이브러리에서 Decision Tree 분류 모형 가져오기
from sklearn import tree


#  의사결정트리 분류기를 생성 (criterion='entropy' 적용)
classifier = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5)


In [8]:
# 분류기 학습
classifier.fit(X_train, y_train)

# 예측
y_pred= classifier.predict(X_test)
print(y_pred)

[0 1 0 ... 0 1 1]


In [9]:
# 작은 이원교차표
from sklearn.metrics import confusion_matrix
conf_matrix= confusion_matrix(y_test, y_pred)
print(conf_matrix)    

[[1072    0]
 [   0  959]]


In [10]:
# 정밀도 , 재현율, f1 score 확인 
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1072
           1       1.00      1.00      1.00       959

    accuracy                           1.00      2031
   macro avg       1.00      1.00      1.00      2031
weighted avg       1.00      1.00      1.00      2031



In [11]:
# 정확도 확인하는 코드 
from sklearn.metrics import accuracy_score
accuracy = accuracy_score( y_test, y_pred)
print(accuracy)  #  1.0   Decision tree 
                 #  0.9497   MultinomialNB
                 #  0.9615   GaussianNB
                 #  0.9350   BernoulliNB

1.0
