In [4]:
import pandas as pd  # 데이터 전처리를 위해서 
import seaborn as sns # 시각화를 위해서 

df = pd.read_csv('c:\\data\\wine.csv')
print(df)

    Type  Alcohol  Malic   Ash  Alcalinity  Magnesium  Phenols  Flavanoids  \
0     t1    14.23   1.71  2.43        15.6        127     2.80        3.06   
1     t1    13.20   1.78  2.14        11.2        100     2.65        2.76   
2     t1    13.16   2.36  2.67        18.6        101     2.80        3.24   
3     t1    14.37   1.95  2.50        16.8        113     3.85        3.49   
4     t1    13.24   2.59  2.87        21.0        118     2.80        2.69   
..   ...      ...    ...   ...         ...        ...      ...         ...   
173   t3    13.71   5.65  2.45        20.5         95     1.68        0.61   
174   t3    13.40   3.91  2.48        23.0        102     1.80        0.75   
175   t3    13.27   4.28  2.26        20.0        120     1.59        0.69   
176   t3    13.17   2.59  2.37        20.0        120     1.65        0.68   
177   t3    14.13   4.10  2.74        24.5         96     2.05        0.76   

     Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Pro

In [5]:
# DataFrame 확인
print(df.shape)  # (178, 14)
print(df.info())  # Type 이 라벨 컬럼 입니다. 
print(df.describe()) # 요약 통계정보를 확인한다. 

(178, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Type             178 non-null    object 
 1   Alcohol          178 non-null    float64
 2   Malic            178 non-null    float64
 3   Ash              178 non-null    float64
 4   Alcalinity       178 non-null    float64
 5   Magnesium        178 non-null    int64  
 6   Phenols          178 non-null    float64
 7   Flavanoids       178 non-null    float64
 8   Nonflavanoids    178 non-null    float64
 9   Proanthocyanins  178 non-null    float64
 10  Color            178 non-null    float64
 11  Hue              178 non-null    float64
 12  Dilution         178 non-null    float64
 13  Proline          178 non-null    int64  
dtypes: float64(11), int64(2), object(1)
memory usage: 19.6+ KB
None
          Alcohol       Malic         Ash  Alcalinity   Magnesium     Phenols  \

In [6]:
# X = 전체 행, 마지막 열 제외한 모든 열 데이터 -> n차원 공간의 포인트
X = df.iloc[:, 1:].to_numpy() 
y = df['Type'].to_numpy()   

print(df.shape)  # (174, 14)
print(len(X))  # 178
print(len(y))  # 178

(178, 14)
178
178


In [7]:
# 정규화 진행                     
from sklearn import preprocessing 

#X=preprocessing.StandardScaler().fit(X).transform(X) 
X=preprocessing.MinMaxScaler().fit(X).transform(X) 

In [8]:
from sklearn.model_selection import train_test_split 
                                                                
# 훈련 데이터 90, 테스트 데이터 10으로 나눈다. 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.1, random_state = 10)

print(X_train.shape) # (160, 13)
print(y_train.shape) # (160, )

(160, 13)
(160,)


In [10]:
# 스케일링(z-score 표준화 수행 결과 확인)
for col in range(4):
    print(f'mean = {X_train[:, col].mean()}, std= {X_train[:, col].std()}')
    
for col in range(4):
    print(f'mean = {X_test[:, col].mean()}, std= {X_test[:, col].std()}')

mean = 0.5180098684210528, std= 0.21175577410451685
mean = 0.32440711462450594, std= 0.22276113616543985
mean = 0.5519719251336898, std= 0.13646540172925498
mean = 0.46990979381443304, std= 0.16861549573199347
mean = 0.523684210526316, std= 0.22404511648272968
mean = 0.23616600790513834, std= 0.17670687066728705
mean = 0.41622103386809267, std= 0.1718849088337324
mean = 0.3571019473081328, std= 0.16501829094638318


In [11]:
# 학습/예측(Training/Pradiction)
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.naive_bayes import GaussianNB
#from sklearn.naive_bayes import MultinomialNB

In [13]:
# 분류기 학습
classifier.fit(X_train, y_train)

# 예측
y_pred= classifier.predict(X_test)
print(y_pred)

['t2' 't2' 't1' 't2' 't1' 't2' 't2' 't1' 't3' 't1' 't1' 't2' 't1' 't2'
 't2' 't2' 't3' 't2']


In [14]:
# 작은 이원교차표
from sklearn.metrics import confusion_matrix
conf_matrix= confusion_matrix(y_test, y_pred)
print(conf_matrix)    


[[ 6  0  0]
 [ 0 10  1]
 [ 0  0  1]]


In [15]:
# 정밀도 , 재현율, f1 score 확인 
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)


              precision    recall  f1-score   support

          t1       1.00      1.00      1.00         6
          t2       1.00      0.91      0.95        11
          t3       0.50      1.00      0.67         1

    accuracy                           0.94        18
   macro avg       0.83      0.97      0.87        18
weighted avg       0.97      0.94      0.95        18



In [16]:
# 정확도 확인하는 코드 
from sklearn.metrics import accuracy_score
accuracy = accuracy_score( y_test, y_pred)
print(accuracy)  

0.9444444444444444
