In [1]:
import pandas as pd  # 데이터 전처리를 위해서 
import seaborn as sns # 시각화를 위해서 

df = pd.read_csv("c:\\data\\wisc_bc_data.csv") 


In [3]:
# DataFrame 확인
#print(df.shape)
#print(df.info()) 
#print(df.describe())
#print(df.iloc[0:5, ])
#print(df.iloc[-5: ,])
#print(df.iloc[ :, [0,1] ]) 
#print(df.iloc[ :, : ]) 

# X = 전체 행, 마지막 열 제외한 모든 열 데이터 -> n차원 공간의 포인트
X = df.iloc[:, 2:].to_numpy() 
print(X)
y = df['diagnosis'].to_numpy()   
print(y)

#print(df.shape)  # (569, 32)
#print(len(X))  # 569
#print(len(y))  # 569
                    

[[1.232e+01 1.239e+01 7.885e+01 ... 9.391e-02 2.827e-01 6.771e-02]
 [1.060e+01 1.895e+01 6.928e+01 ... 7.926e-02 2.940e-01 7.587e-02]
 [1.104e+01 1.683e+01 7.092e+01 ... 7.431e-02 2.998e-01 7.881e-02]
 ...
 [1.528e+01 2.241e+01 9.892e+01 ... 1.226e-01 3.175e-01 9.772e-02]
 [1.453e+01 1.398e+01 9.386e+01 ... 1.069e-01 2.606e-01 7.810e-02]
 [2.137e+01 1.510e+01 1.413e+02 ... 1.966e-01 2.730e-01 8.666e-02]]
['B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'B'
 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B'
 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B'
 'M' 'M' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'M'
 'M' 'B'

In [4]:
from sklearn import preprocessing  

# X=preprocessing.StandardScaler().fit(X).transform(X)  #  scale 함수 적용
X=preprocessing.MinMaxScaler().fit(X).transform(X)      # min/max 함수 적용 
# 기존 정확도:  0.9707602339181286  ----->  0.9883040935672515
# 기존 scale 함수를 이용했을때 보다 정확도가 더 올라갔습니다. 


In [5]:
from sklearn.model_selection import train_test_split 
                                                                
                     
# 훈련 데이터 70, 테스트 데이터 30으로 나눈다. 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state = 10)

print(X_train.shape) 
print(y_train.shape) 




(398, 30)
(398,)


In [7]:
# 스케일링(z-score 표준화 수행 결과 확인)
for col in range(4):
    print(f'mean = {X_train[:, col].mean()}, std= {X_train[:, col].std()}')
    
for col in range(4):
    print(f'mean = {X_test[:, col].mean()}, std= {X_test[:, col].std()}')


mean = 0.3311624143720163, std= 0.1636944610853261
mean = 0.3201185161519467, std= 0.14521871703962505
mean = 0.3254073560394051, std= 0.16436865552607702
mean = 0.21094646083013158, std= 0.14683758331220814
mean = 0.3546529409013249, std= 0.17218692182895046
mean = 0.33291802383876495, std= 0.14517731102191841
mean = 0.35045570067337745, std= 0.1741677359334064
mean = 0.23082361258395195, std= 0.1534780340926073


In [9]:

from sklearn.neighbors import KNeighborsClassifier

# k-NN 분류기를 생성
classifier = KNeighborsClassifier(n_neighbors=12)

In [10]:
# 분류기 학습
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=12)

In [12]:
# 예측
y_pred= classifier.predict(X_test)
print(y_pred)

['M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B'
 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B'
 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'M'
 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'M' 'M' 'B' 'M' 'M' 'M'
 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M'
 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'B' 'M'
 'M' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'M']


In [13]:
# 작은 이원 교차표 출력
from sklearn.metrics import confusion_matrix
conf_matrix= confusion_matrix(y_test, y_pred)
print(conf_matrix)    

[[98  0]
 [ 2 71]]


In [14]:
# 정밀도 , 재현율, f1 score 출력 
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)


              precision    recall  f1-score   support

           B       0.98      1.00      0.99        98
           M       1.00      0.97      0.99        73

    accuracy                           0.99       171
   macro avg       0.99      0.99      0.99       171
weighted avg       0.99      0.99      0.99       171

